/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/FZhZkYKAjte
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function AnotherInitial() {
  return (
    <div className="w-full min-h-screen bg-gradient-to-br from-[#f5f5f5] to-[#e0e0e0] flex flex-col items-center justify-center px-4 py-12 md:px-6 lg:px-8">
      <div className="max-w-3xl w-full space-y-8">
        <div className="text-center space-y-2">
          <h1 className="text-4xl font-bold tracking-tight">Dress Your Dreams</h1>
          <p className="text-muted-foreground text-lg">Generate a one-of-a-kind dress with AI</p>
        </div>
        <div className="relative">
          <Textarea
            placeholder="Describe your dream dress..."
            className="w-full rounded-2xl bg-white p-6 text-lg shadow-lg focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
            rows={4}
          />
          <div className="absolute top-4 left-4 flex items-center gap-2" />
        </div>
        <div className="flex flex-col gap-4 sm:flex-row sm:justify-center">
          <Button>Generate My Dress</Button>
        </div>
        <div className="grid grid-cols-3 gap-4 text-muted-foreground">
          <Button variant="ghost" className="flex items-center justify-center gap-2">
            <FigmaIcon className="w-6 h-6" />
            Formal
          </Button>
          <Button variant="ghost" className="flex items-center justify-center gap-2">
            <PlayIcon className="w-6 h-6" />
            Casual
          </Button>
          <Button variant="ghost" className="flex items-center justify-center gap-2">
            <WineIcon className="w-6 h-6" />
            Vintage
          </Button>
        </div>
      </div>
    </div>
  )
}

function FigmaIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 5.5A3.5 3.5 0 0 1 8.5 2H12v7H8.5A3.5 3.5 0 0 1 5 5.5z" />
      <path d="M12 2h3.5a3.5 3.5 0 1 1 0 7H12V2z" />
      <path d="M12 12.5a3.5 3.5 0 1 1 7 0 3.5 3.5 0 1 1-7 0z" />
      <path d="M5 19.5A3.5 3.5 0 0 1 8.5 16H12v3.5a3.5 3.5 0 1 1-7 0z" />
      <path d="M5 12.5A3.5 3.5 0 0 1 8.5 9H12v7H8.5A3.5 3.5 0 0 1 5 12.5z" />
    </svg>
  )
}


function PlayIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="6 3 20 12 6 21 6 3" />
    </svg>
  )
}


function WineIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 22h8" />
      <path d="M7 10h10" />
      <path d="M12 15v7" />
      <path d="M12 15a5 5 0 0 0 5-5c0-2-.5-4-2-8H9c-1.5 4-2 6-2 8a5 5 0 0 0 5 5Z" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
