/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Z4noAHTgUsW
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function NewInitial() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gradient-to-b from-[#f5f5f5] to-[#e0e0e0]">
      <div className="relative w-full max-w-3xl px-4 sm:px-6 lg:px-8 py-12">
        <h1 className="text-5xl font-bold font-['Playfair Display'] text-[#333] mb-8">Dream Weaver</h1>
        <div className="relative">
          <input
            type="text"
            placeholder="Imagine your dream dress..."
            className="px-6 py-4 rounded-full border-2 border-[#7986cb] focus:outline-none focus:ring-2 focus:ring-[#7986cb] focus:border-[#7986cb] w-full text-2xl font-['Raleway'] text-[#333]"
          />
          <button className="absolute top-1/2 right-4 transform -translate-y-1/2 bg-[#7986cb] hover:bg-[#5c6bc0] text-white font-bold py-3 px-6 rounded-full transition-colors duration-300 flex items-center">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-6 w-6 mr-2"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"
              />
            </svg>
            Generate Dress
          </button>
        </div>
      </div>
      <div className="absolute inset-0 pointer-events-none">
        <div className="absolute top-0 left-0 w-full h-full animate-float-up">
          <div className="w-2 h-2 bg-[#7986cb] rounded-full mx-2 my-2 animate-float-up-delay" />
          <div className="w-3 h-3 bg-[#5c6bc0] rounded-full mx-4 my-4 animate-float-up-delay-2" />
          <div className="w-1 h-1 bg-[#9fa8da] rounded-full mx-6 my-6 animate-float-up-delay-4" />
        </div>
        <video
          className="absolute top-0 left-0 w-full h-full object-cover opacity-10 animate-fade-in"
          autoPlay
          loop
          muted
        >
          <source src="/dress-sketch.mp4" type="video/mp4" />
        </video>
      </div>
    </div>
  )
}
